Made LAPACK lib required in eCLM; Load LAPACK on Marvin (#133)
* eCLM: Updated to beta-0.7
* Load LAPACK on Marvin. Fixes LAPACK `linker error "undefined reference to `dgtsv_'"
* Fixed Marvin's SYSTEMNAME to 'marvin'. Also, prefer $SYSTEMNAME over $(hostname) for nice printing.

Co-authored-by: Marco van Hulten <Marco.van.Hulten@uni-bonn.de>