BuildParFlow: Compiler option `-Wno-unused-variable` for PDAF-builds
Error
```
parflow_pdaf/pfsimulator/parflow_lib/solver_richards.c:1817:16: error:
unused variable ‘pfl_start’ [-Werror=unused-variable]
```

Background: In `PseudoAdvanceRichards`, there are many unused
variables.