CI: Add PDAF builds (#82)
Adding CI builds for
- eCLM-ParFlow-PDAF
- CLM3.5-ParFlow-PDAF

Changes in TSMP2
- BuildParflow: Add `-Wno-unused-variable` for PDAF-related builds
- BuildPDAFMODEL: More sophisticated library loading for SLURM and HYPRE

Update of PDAF
- mainly switching of CLM-standalone code in interface for coupled build

### More information on ParFlow-Compiler option `-Wno-unused-variable` for PDAF-builds

Error
```
parflow_pdaf/pfsimulator/parflow_lib/solver_richards.c:1817:16: error:
unused variable ‘pfl_start’ [-Werror=unused-variable]
```

Background: In `PseudoAdvanceRichards`, there are many unused
variables, which make sense for diffing with `AdvanceRichards`.